[build]
  publish = "."

# Il backend reale è configurato tramite l'endpoint esterno Google Apps Script Web App.
[[redirects]]
  from = "/api/*"
  to = "/index.html"
  status = 200
  force = true

# Reindirizzamento per la Dashboard dello Staff (Barbiere)
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/frontend-dashboard/*"
  to = "/admin.html"
  status = 200

# Reindirizzamento per tutte le altre rotte verso la SPA Clienti
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
